### ISSUE TITLE
OFFileManager:createDirectoryAtPath:createParents:YES fail on Windows

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#68]
OFFileManager:createDirectoryAtPath:createParents:YES fail on Windows when try create parent tree with strange error. Without createParents work fine.

Error:
Failed to create directory <OFURL: file:///C:>: File exists.

One more strange thing: builded with msys throw File exists, but my cross compiled toolchain with latest mingw+winthreads return Permission denied. Different error codes? Or just different error message for same error?

**Comment by Midar** [comment]
I’m guessing they slightly differently implement _wmkdir. But this is something that might be fixed by #67, as it checks for every component of it is a directory - that includes C:\. OTOH since it splits by \, it actually checks for C:, which is always wrong. I guess the real solution here is to have something like isDrive and not do anything with it if it is.

**Comment by Midar** [comment]
Since the path handling is now changed, this is now only broken because of #67. Closing it because it is essentially a duplicate.

**Comment by Midar** [comment]
This now works before #67 is fixed even, due to the improved path handling in file URLs.
