### ISSUE TITLE
OFFileManager:contentsOfDirectoryAtPath return results in random order

### ISSUE THREAD

**Issue by winnydows** [ObjFW/ObjFW#70]
OFFileManager:contentsOfDirectoryAtPath return results in random order (macOS and Linux), but by standards of popular objc frameworks and human logic, function must return sorted array. I know how to sort array, it's just point of perfect for ObjFW.

**Comment by Midar** [comment]
Most of the time, order is not important. Always sorting it would add unnecessary and significant overhead (O(n * log(n))) for the 99% of cases where you don’t care and the order in the file system is sufficient. I’d recommend to just use .sortedArray when you really need it.

**Comment by winnydows** [comment]
Some times order it's not important, but most time files must be orderd by default. Reorder after contentsOfDirectoryAtPath wil do extra work (array > mutable arry or creating new array), order already mutable array before return result will be faster. But not problem, I can create patch one more patch.

**Comment by Midar** [comment]
Are there any other use cases than displaying it to a user? For the common case of doing something with all files in a directory (e.g. to delete them all), order is entirely relevant.

Sorting them after is still n*log(n), but temporary has double the memory usage indeed.

Maybe it makes sense to add an options: here and have one to sort? But then the question remains how to sort: By Unicode? By locale?

**Comment by winnydows** [comment]
Sort same as do default function Sort in array - work fine for me. May be extra option, but why away from standards ? All ObjC like frameworks return sorted arrays. For example check Cocoa. It't always usable in GUI apps, when content returned to user.

**Comment by Midar** [comment]
ObjFW sometimes intentionally diverts from what Cocoa does.

Having thought about this more, I think sorting it by default is a bad idea.

The most common use cases are:
* Iterating over all the files to delete a directory recursively
* Iterating over all the files to process them, e.g. create a ZIP file with all the files.

These all do not rely on the order. All use cases that depend on an order are presenting the result to a user - this means that localized ordering would be required.

If sorting them were free, there would be no harm in sorting them. However, sorting is expensive.

I've mentioned this increasing the complexity from O(n) to O(n*log(n)) before, but let's look at it with a concrete number to make it more obvious how big the difference is. Let's say a directory contains 20000 entries. Sorting it would involve ~ 285754 operations, plus 20000 operations to enumerate the directory. That is a significant overhead to sort it when it is not required, with just 20000 files already taking more than a magnitude longer. However, if it *is* required and you call .sortedArray instead of getting them sorted in-place, that's ~ 305754 operations, plus 20000 operations to enumerate the directory. So for the case where you need sorting, the O(n*log(n)) of the sorting far outweighs the O(n) of the unnecessary copy, almost guaranteed to be minor enough to not make a noticeable difference, whereas for the case where you don't need the sorting, it now took several times longer. And the more files, the bigger that difference will become. Do the same with 200000 files and you'll see how insane it gets.
